"""add required_user_id to approval_workflows

Revision ID: 20260126173308
Revises: 454c59037009
Create Date: 2026-01-26 17:33:08

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260126173308'
down_revision: Union[str, None] = '454c59037009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_workflows') as batch_op:
        batch_op.add_column(sa.Column('required_user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('required_role', existing_type=sa.VARCHAR(), nullable=True) # Make role nullable
        batch_op.create_foreign_key('fk_approval_workflows_users', 'users', ['required_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_workflows') as batch_op:
        batch_op.drop_constraint('fk_approval_workflows_users', type_='foreignkey')
        batch_op.alter_column('required_role', existing_type=sa.VARCHAR(), nullable=False) # Revert nullable if possible (might fail if nulls exist)
        batch_op.drop_column('required_user_id')
    # ### end Alembic commands ###
