"""add required_user_id to approval_workflows

Revision ID: 20260126173308
Revises: 454c59037009
Create Date: 2026-01-26 17:33:08

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import ProgrammingError


# revision identifiers, used by Alembic.
revision: str = '20260126173308'
down_revision: Union[str, None] = '454c59037009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('approval_workflows')]

    with op.batch_alter_table('approval_workflows') as batch_op:
        if 'required_user_id' not in columns:
            try:
                batch_op.add_column(sa.Column('required_user_id', sa.Integer(), nullable=True))
                batch_op.create_foreign_key('fk_approval_workflows_users', 'users', ['required_user_id'], ['id'])
            except ProgrammingError as e:
                # If the column already exists despite the check (race condition or async inspector issue), ignore it
                if "DuplicateColumnError" in str(e) or "already exists" in str(e):
                    print("Column required_user_id already exists, skipping creation.")
                else:
                    raise e
        else:
            print("Column required_user_id detected by inspector, skipping creation.")

        # This part should be safe to run even if already nullable, but let's wrap it too just in case
        try:
            batch_op.alter_column('required_role', existing_type=sa.VARCHAR(), nullable=True) # Make role nullable
        except ProgrammingError:
            pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_workflows') as batch_op:
        batch_op.drop_constraint('fk_approval_workflows_users', type_='foreignkey')
        batch_op.alter_column('required_role', existing_type=sa.VARCHAR(), nullable=False) # Revert nullable if possible (might fail if nulls exist)
        batch_op.drop_column('required_user_id')
    # ### end Alembic commands ###
