"""add_approval_workflow_table

Revision ID: 454c59037009
Revises: d3e4f5g6h7i8
Create Date: 2026-01-26 13:40:07.022393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '454c59037009'
down_revision: Union[str, None] = 'e77a0823d3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the Enum type safely if it doesn't exist
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        approval_action_type = postgresql.ENUM('CREATE', 'TRANSFER', 'WRITE_OFF', name='approvalactiontype')
        approval_action_type.create(bind, checkfirst=True)
    else:
        approval_action_type = sa.Enum('CREATE', 'TRANSFER', 'WRITE_OFF', name='approvalactiontype')

    op.create_table('approval_workflows',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=True),
        # Pass create_type=False to avoid attempting to create it again inside create_table
        # We reuse the same object or define it identically to ensure SQLAlchemy knows it's the same type
        sa.Column('action_type', approval_action_type if bind.dialect.name != 'postgresql' else postgresql.ENUM('CREATE', 'TRANSFER', 'WRITE_OFF', name='approvalactiontype', create_type=False), nullable=True),
        # userrole type already exists, so we define as String first to avoid duplicate type error
        sa.Column('required_role', sa.String(), nullable=True),
        sa.Column('step_order', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_workflows_id'), 'approval_workflows', ['id'], unique=False)

    # Manually cast to existing Enum type for PostgreSQL
    if bind.dialect.name == 'postgresql':
        op.execute("ALTER TABLE approval_workflows ALTER COLUMN required_role TYPE userrole USING required_role::userrole")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_workflows_id'), table_name='approval_workflows')
    op.drop_table('approval_workflows')

    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute("DROP TYPE IF EXISTS approvalactiontype")
    # ### end Alembic commands ###
