"""add_approval_workflow_table

Revision ID: 454c59037009
Revises: d3e4f5g6h7i8
Create Date: 2026-01-26 13:40:07.022393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '454c59037009'
down_revision: Union[str, None] = 'd3e4f5g6h7i8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.Enum('CREATE', 'TRANSFER', 'WRITE_OFF', name='approvalactiontype'), nullable=True),
    # userrole type already exists from users table
    sa.Column('required_role', sa.Enum('ADMIN', 'APPROVER', 'OPERATOR', 'AUDITOR', name='userrole', create_type=False), nullable=True),
    sa.Column('step_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_workflows_id'), 'approval_workflows', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_workflows_id'), table_name='approval_workflows')
    op.drop_table('approval_workflows')
    # ### end Alembic commands ###
