"""add request model

Revision ID: 8c5afbcdaab7
Revises: 3e9d4f69b6dd
Create Date: 2026-01-27 16:04:11.013715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c5afbcdaab7'
down_revision: Union[str, None] = '3e9d4f69b6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    try:
        op.create_table('system_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('key', sa.String(), nullable=True),
        sa.Column('value', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
        op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    except:
        pass # Table might exist

    # 2. Create Requests Table (Safely)
    try:
        op.create_table('requests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.Enum('CREATE', 'TRANSFER', 'WRITE_OFF', name='approvalactiontype'), nullable=True),
        sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=True),
        sa.Column('requester_id', sa.Integer(), nullable=True),
        sa.Column('category_id', sa.Integer(), nullable=True),
        sa.Column('current_step', sa.Integer(), nullable=True),
        sa.Column('data', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_requests_id'), 'requests', ['id'], unique=False)
    except:
        pass

    # 3. Modify Items Table (Batch Mode for SQLite)
    with op.batch_alter_table('items', schema=None) as batch_op:
        # Check if column exists logic difficult in plain alembic without inspection
        # Assuming if table was created, migration state is messy.
        # But `add_column` will fail if exists.
        # Let's trust Alembic context unless partial run.
        # Since last run failed on create_table, items might NOT have been modified yet.
        # But if it failed AFTER creating table?
        # Safe approach: Inspection
        conn = op.get_bind()
        from sqlalchemy.engine.reflection import Inspector
        inspector = Inspector.from_engine(conn)
        columns = [c['name'] for c in inspector.get_columns('items')]

        if 'request_id' not in columns:
            batch_op.add_column(sa.Column('request_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_items_request_id', 'requests', ['request_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('all_branches',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'false'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('all_branches',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'false'"))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_items_request_id', type_='foreignkey')
        batch_op.drop_column('request_id')

    op.drop_index(op.f('ix_requests_id'), table_name='requests')
    op.drop_table('requests')
    try:
        op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
        op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
        op.drop_table('system_settings')
    except:
        pass
    # ### end Alembic commands ###
