"""Add fixed_asset_number to items

Revision ID: add_fixed_asset
Revises: add_user_branch
Create Date: 2023-10-27 13:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_fixed_asset'
down_revision: Union[str, None] = 'add_user_branch'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    with op.batch_alter_table('items') as batch_op:
        batch_op.add_column(sa.Column('fixed_asset_number', sa.String(), nullable=True))
        batch_op.create_index(op.f('ix_items_fixed_asset_number'), ['fixed_asset_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_items_fixed_asset_number'), table_name='items')
    op.drop_column('items', 'fixed_asset_number')
    # ### end Alembic commands ###
